services:
  todo-api:
    build: .
    container_name: todo-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tododb
      - SPRING_DATASOURCE_USERNAME=todo
      - SPRING_DATASOURCE_PASSWORD=todo
      - SWAGGER_ENABLED=true
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: